import { ShowAlertOptions } from '../utils/showAlertOptions'

export const values = {
  button: false,
  setButton: jest.fn(),
  valueGiftCard: 10,
  code: 'code',
  addValueGiftCard: '2',
  setAddValueGiftCard: jest.fn(),
  updateGiftCardFunction: jest.fn(),
  validation: 'text validations',
  setValidation: jest.fn(),
  showAlert: ShowAlertOptions.notShow,
  setShowAlert: jest.fn(),
  handleCloseAlert: jest.fn(),
  credit: 2,
  history: [
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: true,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
    {
      value: 'R$10,00',
      description: '',
      dateAndTime: '10-10-2022',
      status: false,
    },
  ],
  copyCode: jest.fn(),
  loading: false,
  loadingCode: false,
  rescue: 0,
  isGiftCardFieldInvalid: true,
  setIsGiftCardFieldInvalid: jest.fn(),
  loadingGiftCard: false,
  loadingCredit: false,
  loadingRedemptionCode: false,
  loadingHistory: false,
  loadingGetRouteHistory: false,
  setFilterHistory: jest.fn(),
}
