export { default as Alert } from '@vtex/styleguide/lib/Alert'
export { default as Collapsible } from '@vtex/styleguide/lib/Collapsible'
export { default as InputButton } from '@vtex/styleguide/lib/InputButton'
export { default as IconInfo } from '@vtex/styleguide/lib/icon/Info'
export { default as Tooltip } from '@vtex/styleguide/lib/Tooltip'
export { default as Divider } from '@vtex/styleguide/lib/Divider'
export { default as Button } from '@vtex/styleguide/lib/Button'
export { default as Input } from '@vtex/styleguide/lib/Input'
