declare module '@vtex/styleguide/lib/Alert'
declare module '@vtex/styleguide/lib/Collapsible'
declare module '@vtex/styleguide/lib/InputButton'
declare module '@vtex/styleguide/lib/icon/Info'
declare module '@vtex/styleguide/lib/Tooltip'
declare module '@vtex/styleguide/lib/Divider'
declare module '@vtex/styleguide/lib/Button'
declare module '@vtex/styleguide/lib/Input'
